### ISSUE TITLE
RuntimeError: cannot release un-acquired lock

### ISSUE THREAD

**Issue by MikeTheCanuck** [hackoregon/team-budget#128]
As of PR #121, use of `python manage.py runserver` results in **RuntimeError: cannot release un-aquired lock** and related issues, which halts the server and prevents the Python runtime from running our Django code in a localhost 'server'.

This is the stack output we get:

```$ python3 budget_proj/manage.py runserver
Performing system checks...

System check identified no issues (0 silenced).
April 16, 2017 - 16:51:06
Django version 1.10.5, using settings 'budget_proj.settings.dev'
Starting development server at http://127.0.0.1:8000/
Quit the server with CONTROL-C.
/Users/mike/code/~hackoregon/team-budget/budget_proj/budget_proj/wsgi.py:13: RuntimeWarning: Monkey-patching not on the main thread; threading.main_thread().join() will hang from a greenlet
  from gevent import monkey; monkey.patch_all()
Unhandled exception in thread started by <function check_errors.<locals>.wrapper at 0x106feb730>
Traceback (most recent call last):
  File "/Users/mike/code/~hackoregon/team-budget/budget_venv/lib/python3.5/site-packages/django/utils/autoreload.py", line 226, in wrapper
    fn(*args, **kwargs)
  File "/Users/mike/code/~hackoregon/team-budget/budget_venv/lib/python3.5/site-packages/django/core/management/commands/runserver.py", line 142, in inner_run
    handler = self.get_handler(*args, **options)
  File "/Users/mike/code/~hackoregon/team-budget/budget_venv/lib/python3.5/site-packages/django/contrib/staticfiles/management/commands/runserver.py", line 27, in get_handler
    handler = super(Command, self).get_handler(*args, **options)
  File "/Users/mike/code/~hackoregon/team-budget/budget_venv/lib/python3.5/site-packages/django/core/management/commands/runserver.py", line 64, in get_handler
    return get_internal_wsgi_application()
  File "/Users/mike/code/~hackoregon/team-budget/budget_venv/lib/python3.5/site-packages/django/core/servers/basehttp.py", line 49, in get_internal_wsgi_application
    return import_string(app_path)
  File "/Users/mike/code/~hackoregon/team-budget/budget_venv/lib/python3.5/site-packages/django/utils/module_loading.py", line 20, in import_string
    module = import_module(module_path)
  File "/Users/mike/code/~hackoregon/team-budget/budget_venv/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 171, in __exit__
  File "<frozen importlib._bootstrap>", line 123, in release
RuntimeError: cannot release un-acquired lock
```

We know it's due to the use of the `monkey` module's `patch_all()` function from the `gevent` worker; what we don't know is how to leverage the monkey patching capabilities of gevent to stabilize the app in Docker deployments, without interrupting the non-Docker runs of the app.

**Comment by MikeTheCanuck** [comment]
One idea I ran across was to run the python app with the `--noreload` parameter - that enables the app to startup successfully, but any requests it receives will cause an error:

```python
$ python budget_proj/manage.py runserver --noreload
Performing system checks...

System check identified no issues (0 silenced).
April 16, 2017 - 17:31:11
Django version 1.10.5, using settings 'budget_proj.settings.dev'
Starting development server at http://127.0.0.1:8000/
Quit the server with CONTROL-C.
Traceback (most recent call last):
  File "/usr/local/Cellar/python3/3.5.2_3/Frameworks/Python.framework/Versions/3.5/lib/python3.5/wsgiref/handlers.py", line 137, in run
    self.result = application(self.environ, self.start_response)
  File "/Users/mike/code/~hackoregon/team-budget/budget_venv/lib/python3.5/site-packages/django/contrib/staticfiles/handlers.py", line 63, in __call__
    return self.application(environ, start_response)
  File "/Users/mike/code/~hackoregon/team-budget/budget_venv/lib/python3.5/site-packages/django/core/handlers/wsgi.py", line 157, in __call__
    signals.request_started.send(sender=self.__class__, environ=environ)
  File "/Users/mike/code/~hackoregon/team-budget/budget_venv/lib/python3.5/site-packages/django/dispatch/dispatcher.py", line 191, in send
    response = receiver(signal=self, sender=sender, **named)
  File "/Users/mike/code/~hackoregon/team-budget/budget_venv/lib/python3.5/site-packages/django/db/__init__.py", line 61, in close_old_connections
    conn.close_if_unusable_or_obsolete()
  File "/Users/mike/code/~hackoregon/team-budget/budget_venv/lib/python3.5/site-packages/django/db/backends/base/base.py", line 504, in close_if_unusable_or_obsolete
    self.close()
  File "/Users/mike/code/~hackoregon/team-budget/budget_venv/lib/python3.5/site-packages/django/db/backends/base/base.py", line 263, in close
    self.validate_thread_sharing()
  File "/Users/mike/code/~hackoregon/team-budget/budget_venv/lib/python3.5/site-packages/django/db/backends/base/base.py", line 522, in validate_thread_sharing
    % (self.alias, self._thread_ident, thread.get_ident())
django.db.utils.DatabaseError: DatabaseWrapper objects created in a thread can only be used in that same thread. The object with alias 'default' was created in thread id 140735249756160 and this is thread id 4416672120.
[16/Apr/2017 17:31:15] "GET /budget/history/?fiscal_year=2015-16&fund_code=SPEC_REV HTTP/1.1" 500 59
Traceback (most recent call last):
  File "/usr/local/Cellar/python3/3.5.2_3/Frameworks/Python.framework/Versions/3.5/lib/python3.5/wsgiref/handlers.py", line 137, in run
    self.result = application(self.environ, self.start_response)
  File "/Users/mike/code/~hackoregon/team-budget/budget_venv/lib/python3.5/site-packages/django/contrib/staticfiles/handlers.py", line 63, in __call__
    return self.application(environ, start_response)
  File "/Users/mike/code/~hackoregon/team-budget/budget_venv/lib/python3.5/site-packages/django/core/handlers/wsgi.py", line 157, in __call__
    signals.request_started.send(sender=self.__class__, environ=environ)
  File "/Users/mike/code/~hackoregon/team-budget/budget_venv/lib/python3.5/site-packages/django/dispatch/dispatcher.py", line 191, in send
    response = receiver(signal=self, sender=sender, **named)
  File "/Users/mike/code/~hackoregon/team-budget/budget_venv/lib/python3.5/site-packages/django/db/__init__.py", line 61, in close_old_connections
    conn.close_if_unusable_or_obsolete()
  File "/Users/mike/code/~hackoregon/team-budget/budget_venv/lib/python3.5/site-packages/django/db/backends/base/base.py", line 504, in close_if_unusable_or_obsolete
    self.close()
  File "/Users/mike/code/~hackoregon/team-budget/budget_venv/lib/python3.5/site-packages/django/db/backends/base/base.py", line 263, in close
    self.validate_thread_sharing()
  File "/Users/mike/code/~hackoregon/team-budget/budget_venv/lib/python3.5/site-packages/django/db/backends/base/base.py", line 522, in validate_thread_sharing
    % (self.alias, self._thread_ident, thread.get_ident())
django.db.utils.DatabaseError: DatabaseWrapper objects created in a thread can only be used in that same thread. The object with alias 'default' was created in thread id 140735249756160 and this is thread id 4416672120.
[16/Apr/2017 17:31:15] "GET /favicon.ico HTTP/1.1" 500 59
```

**Comment by MikeTheCanuck** [comment]
The most similar bug reported in the **gevent** repo are:
https://github.com/gevent/gevent/issues/615 (fixed two years ago)

**Comment by MikeTheCanuck** [comment]
The most promising idea I've stumbled on is buried here:
http://lists.openstack.org/pipermail/openstack-dev/2012-August/000794.html

Where they pass in `thread=False` to the `patch_all()` function.

It appears that with this parameter setting, the local server will run and serve responses.

It's unclear whether this negates the very stabilization effect that gevent's `monkey.patch_all()` has for our deployed server, but at the moment I'm willing to give it a shot to unblock development.

**Comment by BrianHGrant** [comment]
Played around a little, this pattern works for me locally:

1. set variable in env.sh (or however setting local env variables)
```export DEBUG=True```
2. add to environment variables in docker-compose:
```
environment:
    - DEBUG=${DEBUG}
```
3. in the ```docker-entrypoint.sh```, a if/else to check variable, which server to run (if not using docker then dev just calls the python server)

```
if [ "$DEBUG" == 'True' ]; then
  python manage.py runserver 0.0.0.0:8000
else
  gunicorn emerresponseAPI.wsgi:application -b :8000 -k 'gevent' ...
fi
```

4.in the ```wsgi.py```  short circuit the import and use of monkey-patch/gevent when using dev server:
```
if bool(os.environ.get("DEBUG")) == False:
    from gevent import monkey;
    from psycogreen.gevent import patch_psycopg

    monkey.patch_all()
    patch_psycopg()
```

Since bool(os.environ.get("DEBUG")) will equate to False, unless the env variable is set, this should deploy w/o issues though one could set the DEBUG variable in Travis.
